OFFLINE_WORDS = [
    # ── A1 ──────────────────────────────────────────────────────────────────
    {"id": -1,  "word": "der Hund",    "article": "der", "baseWord": "Hund",    "level": "A1",
     "category": "Animals",   "englishTranslation": "dog",     "arabicTranslation": "كلب",
     "exampleSentenceDe": "Der Hund bellt laut.",      "exampleSentenceEn": "The dog barks loudly.",
     "exampleSentenceAr": "الكلب ينبح بصوت عالٍ.",
     "imageUrl": "https://loremflickr.com/300/300/dog?lock=1"},

    {"id": -2,  "word": "die Katze",   "article": "die", "baseWord": "Katze",   "level": "A1",
     "category": "Animals",   "englishTranslation": "cat",     "arabicTranslation": "قطة",
     "exampleSentenceDe": "Die Katze schläft auf dem Sofa.", "exampleSentenceEn": "The cat sleeps on the sofa.",
     "exampleSentenceAr": "القطة تنام على الأريكة.",
     "imageUrl": "https://loremflickr.com/300/300/cat?lock=2"},

    {"id": -3,  "word": "das Haus",    "article": "das", "baseWord": "Haus",    "level": "A1",
     "category": "Home",      "englishTranslation": "house",   "arabicTranslation": "بيت",
     "exampleSentenceDe": "Das Haus ist groß.",        "exampleSentenceEn": "The house is big.",
     "exampleSentenceAr": "البيت كبير.",
     "imageUrl": "https://loremflickr.com/300/300/house?lock=3"},

    {"id": -4,  "word": "die Küche",   "article": "die", "baseWord": "Küche",   "level": "A1",
     "category": "Home",      "englishTranslation": "kitchen", "arabicTranslation": "مطبخ",
     "exampleSentenceDe": "Die Küche ist sauber.",     "exampleSentenceEn": "The kitchen is clean.",
     "exampleSentenceAr": "المطبخ نظيف.",
     "imageUrl": "https://loremflickr.com/300/300/kitchen?lock=4"},

    {"id": -5,  "word": "das Brot",    "article": "das", "baseWord": "Brot",    "level": "A1",
     "category": "Food",      "englishTranslation": "bread",   "arabicTranslation": "خبز",
     "exampleSentenceDe": "Das Brot ist frisch.",      "exampleSentenceEn": "The bread is fresh.",
     "exampleSentenceAr": "الخبز طازج.",
     "imageUrl": "https://loremflickr.com/300/300/bread?lock=5"},

    {"id": -6,  "word": "das Wasser",  "article": "das", "baseWord": "Wasser",  "level": "A1",
     "category": "Food",      "englishTranslation": "water",   "arabicTranslation": "ماء",
     "exampleSentenceDe": "Ich trinke Wasser.",        "exampleSentenceEn": "I drink water.",
     "exampleSentenceAr": "أنا أشرب الماء.",
     "imageUrl": "https://loremflickr.com/300/300/water?lock=6"},

    {"id": -7,  "word": "das Auto",    "article": "das", "baseWord": "Auto",    "level": "A1",
     "category": "Transport", "englishTranslation": "car",     "arabicTranslation": "سيارة",
     "exampleSentenceDe": "Das Auto ist rot.",         "exampleSentenceEn": "The car is red.",
     "exampleSentenceAr": "السيارة حمراء.",
     "imageUrl": "https://loremflickr.com/300/300/car?lock=7"},

    {"id": -8,  "word": "die Schule",  "article": "die", "baseWord": "Schule",  "level": "A1",
     "category": "Education", "englishTranslation": "school",  "arabicTranslation": "مدرسة",
     "exampleSentenceDe": "Die Schule beginnt um acht.", "exampleSentenceEn": "School starts at eight.",
     "exampleSentenceAr": "تبدأ المدرسة الساعة الثامنة.",
     "imageUrl": "https://loremflickr.com/300/300/school?lock=8"},

    {"id": -9,  "word": "das Kind",    "article": "das", "baseWord": "Kind",    "level": "A1",
     "category": "People",    "englishTranslation": "child",   "arabicTranslation": "طفل",
     "exampleSentenceDe": "Das Kind spielt im Garten.", "exampleSentenceEn": "The child plays in the garden.",
     "exampleSentenceAr": "الطفل يلعب في الحديقة.",
     "imageUrl": "https://loremflickr.com/300/300/child?lock=9"},

    {"id": -10, "word": "der Tisch",   "article": "der", "baseWord": "Tisch",   "level": "A1",
     "category": "Home",      "englishTranslation": "table",   "arabicTranslation": "طاولة",
     "exampleSentenceDe": "Der Tisch ist aus Holz.",   "exampleSentenceEn": "The table is made of wood.",
     "exampleSentenceAr": "الطاولة مصنوعة من الخشب.",
     "imageUrl": "https://loremflickr.com/300/300/table?lock=10"},

    # ── A2 ──────────────────────────────────────────────────────────────────
    {"id": -11, "word": "der Bahnhof",   "article": "der", "baseWord": "Bahnhof",   "level": "A2",
     "category": "Travel",    "englishTranslation": "train station", "arabicTranslation": "محطة القطار",
     "exampleSentenceDe": "Wir treffen uns am Bahnhof.", "exampleSentenceEn": "We meet at the train station.",
     "exampleSentenceAr": "نلتقي في محطة القطار.",
     "imageUrl": "https://loremflickr.com/300/300/train-station?lock=11"},

    {"id": -12, "word": "die Fahrkarte", "article": "die", "baseWord": "Fahrkarte", "level": "A2",
     "category": "Travel",    "englishTranslation": "ticket",  "arabicTranslation": "تذكرة",
     "exampleSentenceDe": "Ich kaufe eine Fahrkarte.", "exampleSentenceEn": "I buy a ticket.",
     "exampleSentenceAr": "أشتري تذكرة.",
     "imageUrl": "https://loremflickr.com/300/300/train-ticket?lock=12"},

    {"id": -13, "word": "das Restaurant","article": "das", "baseWord": "Restaurant","level": "A2",
     "category": "Food",      "englishTranslation": "restaurant","arabicTranslation": "مطعم",
     "exampleSentenceDe": "Das Restaurant ist voll.",  "exampleSentenceEn": "The restaurant is full.",
     "exampleSentenceAr": "المطعم ممتلئ.",
     "imageUrl": "https://loremflickr.com/300/300/restaurant?lock=13"},

    {"id": -14, "word": "der Supermarkt","article": "der", "baseWord": "Supermarkt","level": "A2",
     "category": "Shopping",  "englishTranslation": "supermarket","arabicTranslation": "سوبرماركت",
     "exampleSentenceDe": "Ich gehe in den Supermarkt.", "exampleSentenceEn": "I go to the supermarket.",
     "exampleSentenceAr": "أذهب إلى السوبرماركت.",
     "imageUrl": "https://loremflickr.com/300/300/supermarket?lock=14"},

    {"id": -15, "word": "der Arzt",      "article": "der", "baseWord": "Arzt",      "level": "A2",
     "category": "Health",    "englishTranslation": "doctor",  "arabicTranslation": "طبيب",
     "exampleSentenceDe": "Der Arzt hilft dem Patienten.", "exampleSentenceEn": "The doctor helps the patient.",
     "exampleSentenceAr": "الطبيب يساعد المريض.",
     "imageUrl": "https://loremflickr.com/300/300/doctor?lock=15"},

    {"id": -16, "word": "das Krankenhaus","article":"das", "baseWord":"Krankenhaus","level": "A2",
     "category": "Health",    "englishTranslation": "hospital","arabicTranslation": "مستشفى",
     "exampleSentenceDe": "Das Krankenhaus ist neu.",  "exampleSentenceEn": "The hospital is new.",
     "exampleSentenceAr": "المستشفى جديد.",
     "imageUrl": "https://loremflickr.com/300/300/hospital?lock=16"},

    {"id": -17, "word": "das Wetter",    "article": "das", "baseWord": "Wetter",    "level": "A2",
     "category": "Nature",    "englishTranslation": "weather", "arabicTranslation": "طقس",
     "exampleSentenceDe": "Das Wetter ist schön heute.", "exampleSentenceEn": "The weather is nice today.",
     "exampleSentenceAr": "الطقس جميل اليوم.",
     "imageUrl": "https://loremflickr.com/300/300/weather,sky?lock=17"},

    {"id": -18, "word": "die Straße",    "article": "die", "baseWord": "Straße",    "level": "A2",
     "category": "City",      "englishTranslation": "street",  "arabicTranslation": "شارع",
     "exampleSentenceDe": "Die Straße ist breit.",     "exampleSentenceEn": "The street is wide.",
     "exampleSentenceAr": "الشارع واسع.",
     "imageUrl": "https://loremflickr.com/300/300/street?lock=18"},

    {"id": -19, "word": "das Büro",      "article": "das", "baseWord": "Büro",      "level": "A2",
     "category": "Work",      "englishTranslation": "office",  "arabicTranslation": "مكتب",
     "exampleSentenceDe": "Das Büro ist im dritten Stock.", "exampleSentenceEn": "The office is on the third floor.",
     "exampleSentenceAr": "المكتب في الطابق الثالث.",
     "imageUrl": "https://loremflickr.com/300/300/office?lock=19"},

    {"id": -20, "word": "das Telefon",   "article": "das", "baseWord": "Telefon",   "level": "A2",
     "category": "Technology","englishTranslation": "telephone","arabicTranslation": "هاتف",
     "exampleSentenceDe": "Das Telefon klingelt.",     "exampleSentenceEn": "The telephone rings.",
     "exampleSentenceAr": "الهاتف يرن.",
     "imageUrl": "https://loremflickr.com/300/300/telephone?lock=20"},

    # ── B1 ──────────────────────────────────────────────────────────────────
    {"id": -21, "word": "die Besprechung","article":"die","baseWord":"Besprechung","level": "B1",
     "category": "Work",      "englishTranslation": "meeting", "arabicTranslation": "اجتماع",
     "exampleSentenceDe": "Die Besprechung dauert zwei Stunden.", "exampleSentenceEn": "The meeting lasts two hours.",
     "exampleSentenceAr": "الاجتماع يستمر ساعتين.",
     "imageUrl": "https://loremflickr.com/300/300/meeting,business?lock=21"},

    {"id": -22, "word": "der Lebenslauf","article":"der","baseWord":"Lebenslauf","level": "B1",
     "category": "Work",      "englishTranslation": "CV / résumé","arabicTranslation": "سيرة ذاتية",
     "exampleSentenceDe": "Bitte schicken Sie Ihren Lebenslauf.", "exampleSentenceEn": "Please send your CV.",
     "exampleSentenceAr": "يرجى إرسال سيرتك الذاتية.",
     "imageUrl": "https://loremflickr.com/300/300/resume,document?lock=22"},

    {"id": -23, "word": "der Vertrag",   "article": "der", "baseWord": "Vertrag",   "level": "B1",
     "category": "Work",      "englishTranslation": "contract","arabicTranslation": "عقد",
     "exampleSentenceDe": "Der Vertrag wird morgen unterschrieben.", "exampleSentenceEn": "The contract will be signed tomorrow.",
     "exampleSentenceAr": "سيُوقَّع العقد غداً.",
     "imageUrl": "https://loremflickr.com/300/300/contract,sign?lock=23"},

    {"id": -24, "word": "die Erfahrung", "article": "die", "baseWord": "Erfahrung", "level": "B1",
     "category": "Work",      "englishTranslation": "experience","arabicTranslation": "خبرة",
     "exampleSentenceDe": "Er hat viel Erfahrung im Bereich Marketing.", "exampleSentenceEn": "He has a lot of experience in marketing.",
     "exampleSentenceAr": "لديه خبرة واسعة في مجال التسويق.",
     "imageUrl": None},

    {"id": -25, "word": "die Gelegenheit","article":"die","baseWord":"Gelegenheit","level": "B1",
     "category": "Abstract",  "englishTranslation": "opportunity","arabicTranslation": "فرصة",
     "exampleSentenceDe": "Das ist eine gute Gelegenheit.", "exampleSentenceEn": "This is a good opportunity.",
     "exampleSentenceAr": "هذه فرصة جيدة.",
     "imageUrl": None},

    {"id": -26, "word": "die Verantwortung","article":"die","baseWord":"Verantwortung","level":"B1",
     "category": "Abstract",  "englishTranslation": "responsibility","arabicTranslation": "مسؤولية",
     "exampleSentenceDe": "Er trägt große Verantwortung.", "exampleSentenceEn": "He carries great responsibility.",
     "exampleSentenceAr": "يتحمل مسؤولية كبيرة.",
     "imageUrl": None},

    {"id": -27, "word": "die Entwicklung","article":"die","baseWord":"Entwicklung","level": "B1",
     "category": "Abstract",  "englishTranslation": "development","arabicTranslation": "تطوير",
     "exampleSentenceDe": "Die Entwicklung der Technik ist schnell.", "exampleSentenceEn": "Technological development is fast.",
     "exampleSentenceAr": "التطور التكنولوجي سريع.",
     "imageUrl": "https://loremflickr.com/300/300/technology,development?lock=27"},

    {"id": -28, "word": "die Gesellschaft","article":"die","baseWord":"Gesellschaft","level":"B1",
     "category": "Society",   "englishTranslation": "society", "arabicTranslation": "مجتمع",
     "exampleSentenceDe": "Die Gesellschaft muss sich ändern.", "exampleSentenceEn": "Society must change.",
     "exampleSentenceAr": "يجب أن يتغير المجتمع.",
     "imageUrl": "https://loremflickr.com/300/300/society,people?lock=28"},

    {"id": -29, "word": "die Entscheidung","article":"die","baseWord":"Entscheidung","level":"B1",
     "category": "Abstract",  "englishTranslation": "decision","arabicTranslation": "قرار",
     "exampleSentenceDe": "Die Entscheidung war schwierig.", "exampleSentenceEn": "The decision was difficult.",
     "exampleSentenceAr": "كان القرار صعباً.",
     "imageUrl": None},

    {"id": -30, "word": "die Bedeutung", "article": "die", "baseWord": "Bedeutung", "level": "B1",
     "category": "Abstract",  "englishTranslation": "meaning / importance","arabicTranslation": "معنى / أهمية",
     "exampleSentenceDe": "Das hat eine große Bedeutung.", "exampleSentenceEn": "This has great importance.",
     "exampleSentenceAr": "هذا له أهمية كبيرة.",
     "imageUrl": None},

    # ── B2 ──────────────────────────────────────────────────────────────────
    {"id": -31, "word": "die Nachhaltigkeit","article":"die","baseWord":"Nachhaltigkeit","level":"B2",
     "category": "Environment","englishTranslation":"sustainability","arabicTranslation":"الاستدامة",
     "exampleSentenceDe":"Nachhaltigkeit ist ein wichtiges Ziel.", "exampleSentenceEn":"Sustainability is an important goal.",
     "exampleSentenceAr":"الاستدامة هدف مهم.",
     "imageUrl": "https://loremflickr.com/300/300/sustainability,green?lock=31"},

    {"id": -32, "word": "die Globalisierung","article":"die","baseWord":"Globalisierung","level":"B2",
     "category": "Society",   "englishTranslation":"globalization","arabicTranslation":"العولمة",
     "exampleSentenceDe":"Die Globalisierung verändert die Welt.", "exampleSentenceEn":"Globalization changes the world.",
     "exampleSentenceAr":"العولمة تغير العالم.",
     "imageUrl": "https://loremflickr.com/300/300/globe,world?lock=32"},

    {"id": -33, "word": "die Wirtschaft",  "article":"die","baseWord":"Wirtschaft",  "level":"B2",
     "category": "Economics", "englishTranslation":"economy",      "arabicTranslation":"الاقتصاد",
     "exampleSentenceDe":"Die Wirtschaft wächst langsam.", "exampleSentenceEn":"The economy is growing slowly.",
     "exampleSentenceAr":"الاقتصاد ينمو ببطء.",
     "imageUrl": "https://loremflickr.com/300/300/economy,finance?lock=33"},

    {"id": -34, "word": "die Umwelt",      "article":"die","baseWord":"Umwelt",      "level":"B2",
     "category": "Environment","englishTranslation":"environment","arabicTranslation":"البيئة",
     "exampleSentenceDe":"Wir müssen die Umwelt schützen.", "exampleSentenceEn":"We must protect the environment.",
     "exampleSentenceAr":"يجب علينا حماية البيئة.",
     "imageUrl": "https://loremflickr.com/300/300/environment,nature?lock=34"},

    {"id": -35, "word": "die Bevölkerung", "article":"die","baseWord":"Bevölkerung", "level":"B2",
     "category": "Society",   "englishTranslation":"population",  "arabicTranslation":"السكان",
     "exampleSentenceDe":"Die Bevölkerung wächst.", "exampleSentenceEn":"The population is growing.",
     "exampleSentenceAr":"يتزايد عدد السكان.",
     "imageUrl": "https://loremflickr.com/300/300/crowd,people?lock=35"},

    {"id": -36, "word": "die Demokratie",  "article":"die","baseWord":"Demokratie",  "level":"B2",
     "category": "Politics",  "englishTranslation":"democracy",   "arabicTranslation":"الديمقراطية",
     "exampleSentenceDe":"Die Demokratie braucht aktive Bürger.", "exampleSentenceEn":"Democracy needs active citizens.",
     "exampleSentenceAr":"الديمقراطية تحتاج مواطنين نشطين.",
     "imageUrl": "https://loremflickr.com/300/300/democracy,vote?lock=36"},

    {"id": -37, "word": "die Infrastruktur","article":"die","baseWord":"Infrastruktur","level":"B2",
     "category": "Society",   "englishTranslation":"infrastructure","arabicTranslation":"البنية التحتية",
     "exampleSentenceDe":"Die Infrastruktur muss verbessert werden.", "exampleSentenceEn":"The infrastructure must be improved.",
     "exampleSentenceAr":"يجب تحسين البنية التحتية.",
     "imageUrl": "https://loremflickr.com/300/300/infrastructure,bridge?lock=37"},

    {"id": -38, "word": "das Bewusstsein", "article":"das","baseWord":"Bewusstsein", "level":"B2",
     "category": "Abstract",  "englishTranslation":"awareness / consciousness","arabicTranslation":"الوعي",
     "exampleSentenceDe":"Das Bewusstsein für Umweltfragen wächst.", "exampleSentenceEn":"Awareness of environmental issues is growing.",
     "exampleSentenceAr":"يتنامى الوعي بالقضايا البيئية.",
     "imageUrl": None},

    {"id": -39, "word": "die Gleichberechtigung","article":"die","baseWord":"Gleichberechtigung","level":"B2",
     "category": "Society",   "englishTranslation":"equality of rights","arabicTranslation":"المساواة في الحقوق",
     "exampleSentenceDe":"Gleichberechtigung ist ein Grundrecht.", "exampleSentenceEn":"Equal rights are a fundamental right.",
     "exampleSentenceAr":"المساواة في الحقوق حق أساسي.",
     "imageUrl": "https://loremflickr.com/300/300/equality,rights?lock=39"},

    {"id": -40, "word": "die Integration",  "article":"die","baseWord":"Integration",  "level":"B2",
     "category": "Society",   "englishTranslation":"integration",  "arabicTranslation":"الاندماج",
     "exampleSentenceDe":"Integration braucht Zeit und Geduld.", "exampleSentenceEn":"Integration takes time and patience.",
     "exampleSentenceAr":"يحتاج الاندماج إلى وقت وصبر.",
     "imageUrl": None},

    # ── C1 ──────────────────────────────────────────────────────────────────
    {"id": -41, "word": "die Empirie",       "article":"die","baseWord":"Empirie",       "level":"C1",
     "category": "Academic",  "englishTranslation":"empiricism / empirical data","arabicTranslation":"التجريبية",
     "exampleSentenceDe":"Die Studie stützt sich auf solide Empirie.", "exampleSentenceEn":"The study relies on solid empirical data.",
     "exampleSentenceAr":"تستند الدراسة إلى بيانات تجريبية راسخة.",
     "imageUrl": "https://loremflickr.com/300/300/laboratory,research?lock=41"},

    {"id": -42, "word": "die Hypothese",     "article":"die","baseWord":"Hypothese",     "level":"C1",
     "category": "Academic",  "englishTranslation":"hypothesis",   "arabicTranslation":"فرضية",
     "exampleSentenceDe":"Die Hypothese muss überprüft werden.", "exampleSentenceEn":"The hypothesis must be tested.",
     "exampleSentenceAr":"يجب اختبار الفرضية.",
     "imageUrl": "https://loremflickr.com/300/300/science,experiment?lock=42"},

    {"id": -43, "word": "das Paradigma",     "article":"das","baseWord":"Paradigma",     "level":"C1",
     "category": "Academic",  "englishTranslation":"paradigm",     "arabicTranslation":"نموذج / بارادايم",
     "exampleSentenceDe":"Ein neues Paradigma verändert die Wissenschaft.", "exampleSentenceEn":"A new paradigm changes science.",
     "exampleSentenceAr":"يُغيِّر النموذج الجديد مسار العلوم.",
     "imageUrl": None},

    {"id": -44, "word": "die Epistemologie", "article":"die","baseWord":"Epistemologie", "level":"C1",
     "category": "Academic",  "englishTranslation":"epistemology", "arabicTranslation":"نظرية المعرفة",
     "exampleSentenceDe":"Die Epistemologie untersucht die Grundlagen des Wissens.", "exampleSentenceEn":"Epistemology studies the foundations of knowledge.",
     "exampleSentenceAr":"تدرس نظرية المعرفة أسس المعرفة الإنسانية.",
     "imageUrl": None},

    {"id": -45, "word": "die Methodologie",  "article":"die","baseWord":"Methodologie",  "level":"C1",
     "category": "Academic",  "englishTranslation":"methodology",  "arabicTranslation":"منهجية",
     "exampleSentenceDe":"Die Methodologie der Studie ist klar.", "exampleSentenceEn":"The methodology of the study is clear.",
     "exampleSentenceAr":"منهجية الدراسة واضحة.",
     "imageUrl": None},

    {"id": -46, "word": "die Evidenz",       "article":"die","baseWord":"Evidenz",       "level":"C1",
     "category": "Academic",  "englishTranslation":"evidence",     "arabicTranslation":"الدليل / الأدلة",
     "exampleSentenceDe":"Es gibt starke Evidenz dafür.", "exampleSentenceEn":"There is strong evidence for this.",
     "exampleSentenceAr":"توجد أدلة قوية على ذلك.",
     "imageUrl": "https://loremflickr.com/300/300/evidence,research?lock=46"},

    {"id": -47, "word": "die Reflexivität",  "article":"die","baseWord":"Reflexivität",  "level":"C1",
     "category": "Academic",  "englishTranslation":"reflexivity",  "arabicTranslation":"التفكير النقذي الذاتي",
     "exampleSentenceDe":"Reflexivität ist in der qualitativen Forschung wichtig.", "exampleSentenceEn":"Reflexivity is important in qualitative research.",
     "exampleSentenceAr":"التفكير النقدي الذاتي مهم في البحث النوعي.",
     "imageUrl": None},

    {"id": -48, "word": "das Phänomen",      "article":"das","baseWord":"Phänomen",      "level":"C1",
     "category": "Academic",  "englishTranslation":"phenomenon",   "arabicTranslation":"ظاهرة",
     "exampleSentenceDe":"Dieses Phänomen ist schwer zu erklären.", "exampleSentenceEn":"This phenomenon is hard to explain.",
     "exampleSentenceAr":"هذه الظاهرة يصعب تفسيرها.",
     "imageUrl": "https://loremflickr.com/300/300/phenomenon,nature?lock=48"},

    {"id": -49, "word": "die Interdisziplinarität","article":"die","baseWord":"Interdisziplinarität","level":"C1",
     "category": "Academic",  "englishTranslation":"interdisciplinarity","arabicTranslation":"التعددية التخصصية",
     "exampleSentenceDe":"Interdisziplinarität fördert Innovation.", "exampleSentenceEn":"Interdisciplinarity promotes innovation.",
     "exampleSentenceAr":"التعددية التخصصية تعزز الابتكار.",
     "imageUrl": None},

    {"id": -50, "word": "validieren",         "article": None,  "baseWord":"validieren",  "level":"C1",
     "category": "Academic",  "englishTranslation":"to validate",  "arabicTranslation":"يُتحقَّق من صحته",
     "exampleSentenceDe":"Das Instrument muss validiert werden.", "exampleSentenceEn":"The instrument must be validated.",
     "exampleSentenceAr":"يجب التحقق من صحة الأداة.",
     "imageUrl": None},
]
