/**
 * German CEFR word-level lookup table.
 *
 * Compiled from:
 *  - Goethe-Institut official vocabulary lists (A1, A2, B1)
 *  - CEFRLex German frequency-based CEFR mapping
 *  - KELLY project German word list
 *  - Frequency analysis (dwds.de) for B2/C1
 *
 * Keys are lowercase base words WITHOUT articles.
 * Values are CEFR levels: "A1" | "A2" | "B1" | "B2" | "C1".
 *
 * Usage:
 *   import { lookupCefrLevel, correctLevel } from "@workspace/content";
 *   const level = lookupCefrLevel("hund"); // → "A1"
 *   const corrected = correctLevel("die Herausforderung", "C1"); // → "B1"
 */

// ---------------------------------------------------------------------------
// Word → CEFR level map (lowercase base word, no article)
// ---------------------------------------------------------------------------
const CEFR_MAP: Record<string, string> = {
  // ── A1 ───────────────────────────────────────────────────────────────────
  // Greetings & basics
  hallo: "A1",
  tschüss: "A1",
  bitte: "A1",
  danke: "A1",
  ja: "A1",
  nein: "A1",
  ich: "A1",
  du: "A1",
  er: "A1",
  sie: "A1",
  wir: "A1",
  ihr: "A1",
  // Core verbs
  sein: "A1",
  haben: "A1",
  werden: "A1",
  können: "A1",
  müssen: "A1",
  wollen: "A1",
  sollen: "A1",
  dürfen: "A1",
  mögen: "A1",
  machen: "A1",
  gehen: "A1",
  kommen: "A1",
  sehen: "A1",
  sagen: "A1",
  geben: "A1",
  nehmen: "A1",
  wissen: "A1",
  denken: "A1",
  finden: "A1",
  bleiben: "A1",
  stehen: "A1",
  liegen: "A1",
  sitzen: "A1",
  laufen: "A1",
  heißen: "A1",
  wohnen: "A1",
  leben: "A1",
  spielen: "A1",
  lernen: "A1",
  arbeiten: "A1",
  lesen: "A1",
  schreiben: "A1",
  hören: "A1",
  sprechen: "A1",
  essen: "A1",
  trinken: "A1",
  kaufen: "A1",
  schlafen: "A1",
  öffnen: "A1",
  schließen: "A1",
  // Animals
  hund: "A1",
  katze: "A1",
  vogel: "A1",
  fisch: "A1",
  pferd: "A1",
  maus: "A1",
  kuh: "A1",
  schwein: "A1",
  // People & family
  mann: "A1",
  frau: "A1",
  kind: "A1",
  mutter: "A1",
  vater: "A1",
  eltern: "A1",
  bruder: "A1",
  schwester: "A1",
  oma: "A1",
  opa: "A1",
  baby: "A1",
  junge: "A1",
  mädchen: "A1",
  person: "A1",
  leute: "A1",
  mensch: "A1",
  // Home & objects
  haus: "A1",
  wohnung: "A1",
  zimmer: "A1",
  küche: "A1",
  bad: "A1",
  schlafzimmer: "A1",
  wohnzimmer: "A1",
  tisch: "A1",
  stuhl: "A1",
  bett: "A1",
  tür: "A1",
  fenster: "A1",
  lampe: "A1",
  buch: "A1",
  stift: "A1",
  tasche: "A1",
  uhr: "A1",
  computer: "A1",
  telefon: "A1",
  handy: "A1",
  // Food & drink
  wasser: "A1",
  brot: "A1",
  milch: "A1",
  kaffee: "A1",
  tee: "A1",
  apfel: "A1",
  banane: "A1",
  orange: "A1",
  käse: "A1",
  fleisch: "A1",
  gemüse: "A1",
  obst: "A1",
  ei: "A1",
  zucker: "A1",
  salz: "A1",
  öl: "A1",
  suppe: "A1",
  kuchen: "A1",
  // Places
  schule: "A1",
  kindergarten: "A1",
  universität: "A1",
  krankenhaus: "A1",
  supermarkt: "A1",
  restaurant: "A1",
  café: "A1",
  hotel: "A1",
  park: "A1",
  straße: "A1",
  platz: "A1",
  land: "A1",
  stadt: "A1",
  // Colors
  rot: "A1",
  blau: "A1",
  grün: "A1",
  gelb: "A1",
  schwarz: "A1",
  weiß: "A1",
  braun: "A1",
  grau: "A1",
  lila: "A1",
  rosa: "A1",
  // Adjectives (basic)
  gut: "A1",
  schlecht: "A1",
  groß: "A1",
  klein: "A1",
  neu: "A1",
  alt: "A1",
  jung: "A1",
  schön: "A1",
  hässlich: "A1",
  lang: "A1",
  kurz: "A1",
  schnell: "A1",
  langsam: "A1",
  heiß: "A1",
  kalt: "A1",
  warm: "A1",
  lecker: "A1",
  richtig: "A1",
  falsch: "A1",
  leicht: "A1",
  schwer: "A1",
  müde: "A1",
  krank: "A1",
  gesund: "A1",
  glücklich: "A1",
  traurig: "A1",
  // Numbers & time
  tag: "A1",
  woche: "A1",
  monat: "A1",
  jahr: "A1",
  stunde: "A1",
  minute: "A1",
  morgen: "A1",
  mittag: "A1",
  abend: "A1",
  nacht: "A1",
  heute: "A1",
  gestern: "A1",
  // Prepositions / basic connectors
  und: "A1",
  oder: "A1",
  aber: "A1",
  mit: "A1",
  ohne: "A1",
  für: "A1",
  von: "A1",
  // ── A2 ───────────────────────────────────────────────────────────────────
  // Verbs
  erklären: "A2",
  verstehen: "A2",
  antworten: "A2",
  fragen: "A2",
  helfen: "A2",
  zeigen: "A2",
  besuchen: "A2",
  buchen: "A2",
  bezahlen: "A2",
  kochen: "A2",
  backen: "A2",
  waschen: "A2",
  putzen: "A2",
  aufräumen: "A2",
  einladen: "A2",
  warten: "A2",
  kennen: "A2",
  kennenlernen: "A2",
  vorstellen: "A2",
  vergessen: "A2",
  einkaufen: "A2",
  reisen: "A2",
  ankommen: "A2",
  abfahren: "A2",
  umsteigen: "A2",
  wechseln: "A2",
  suchen: "A2",
  verlieren: "A2",
  // People & social
  freund: "A2",
  freundin: "A2",
  nachbar: "A2",
  // Travel & transport
  bahnhof: "A2",
  fahrkarte: "A2",
  zug: "A2",
  bus: "A2",
  auto: "A2",
  flugzeug: "A2",
  fahrrad: "A2",
  taxi: "A2",
  ticket: "A2",
  gepäck: "A2",
  koffer: "A2",
  reise: "A2",
  urlaub: "A2",
  // Health & pharmacy
  arzt: "A2",
  ärztin: "A2",
  apotheke: "A2",
  medikament: "A2",
  rezept: "A2",
  schmerz: "A2",
  erkältung: "A2",
  fieber: "A2",
  einnehmen: "A2",
  // Work & education
  arbeit: "A2",
  beruf: "A2",
  büro: "A2",
  chef: "A2",
  gehalt: "A2",
  unterricht: "A2",
  klasse: "A2",
  lehrer: "A2",
  schüler: "A2",
  hausaufgabe: "A2",
  prüfung: "A2",
  // Shopping & money
  preis: "A2",
  geld: "A2",
  euro: "A2",
  rechnung: "A2",
  kasse: "A2",
  rabatt: "A2",
  angebot: "A2",
  // Housing
  miete: "A2",
  möbel: "A2",
  kühlschrank: "A2",
  herd: "A2",
  waschmaschine: "A2",
  // Communication
  brief: "A2",
  email: "A2",
  nachricht: "A2",
  gespräch: "A2",
  termin: "A2",
  // Adjectives A2
  laut: "A2",
  leise: "A2",
  teuer: "A2",
  billig: "A2",
  frei: "A2",
  besetzt: "A2",
  offen: "A2",
  geschlossen: "A2",
  fertig: "A2",
  wichtig: "A2",
  interessant: "A2",
  langweilig: "A2",
  schwierig: "A2",
  einfach: "A2",
  // Food A2
  frühstück: "A2",
  mittagessen: "A2",
  abendessen: "A2",
  speisekarte: "A2",
  // Nature & weather
  wetter: "A2",
  sonne: "A2",
  regen: "A2",
  schnee: "A2",
  wind: "A2",
  wolke: "A2",
  temperatur: "A2",
  // ── B1 ───────────────────────────────────────────────────────────────────
  // Verbs
  beeinflussen: "B1",
  überzeugen: "B1",
  vermeiden: "B1",
  erreichen: "B1",
  verbessern: "B1",
  entwickeln: "B1",
  planen: "B1",
  entscheiden: "B1",
  lösen: "B1",
  beschreiben: "B1",
  vergleichen: "B1",
  analysieren: "B1",
  diskutieren: "B1",
  argumentieren: "B1",
  informieren: "B1",
  organisieren: "B1",
  vorbereiten: "B1",
  teilnehmen: "B1",
  kündigen: "B1",
  bewerben: "B1",
  verwalten: "B1",
  betreuen: "B1",
  unterstützen: "B1",
  kommunizieren: "B1",
  // Nouns B1
  herausforderung: "B1",
  voraussetzung: "B1",
  fortschritt: "B1",
  umwelt: "B1",
  zusammenhang: "B1",
  verantwortung: "B1",
  gleichberechtigung: "B1",
  meinung: "B1",
  erfahrung: "B1",
  möglichkeit: "B1",
  entscheidung: "B1",
  entwicklung: "B1",
  lösung: "B1",
  problem: "B1",
  thema: "B1",
  beispiel: "B1",
  grund: "B1",
  ziel: "B1",
  vorteil: "B1",
  nachteil: "B1",
  unterschied: "B1",
  zusammenarbeit: "B1",
  verhältnis: "B1",
  situation: "B1",
  gesellschaft: "B1",
  umgebung: "B1",
  gesundheit: "A2",
  lebenslauf: "B1",
  besprechung: "B1",
  bewerbung: "B1",
  ausbildung: "B1",
  weiterbildung: "B1",
  praktikum: "B1",
  stelle: "B1",
  vertrag: "B1",
  versicherung: "B1",
  steuer: "B1",
  bericht: "B1",
  ergebnis: "B1",
  erfolg: "B1",
  misserfolg: "B1",
  // Adjectives B1
  notwendig: "B1",
  möglich: "B1",
  unmöglich: "B1",
  positiv: "B1",
  negativ: "B1",
  ähnlich: "B1",
  verschieden: "B1",
  persönlich: "B1",
  öffentlich: "B1",
  privat: "B1",
  sozial: "B1",
  politisch: "B1",
  wirtschaftlich: "B1",
  kulturell: "B1",
  gesetzlich: "B1",
  beruflich: "B1",
  // ── B2 ───────────────────────────────────────────────────────────────────
  // Verbs B2
  anzweifeln: "B2",
  berücksichtigen: "B2",
  nachhaltig: "B2",
  bewältigen: "B2",
  integrieren: "B2",
  umsetzen: "B2",
  einschätzen: "B2",
  abwägen: "B2",
  strukturieren: "B2",
  differenzieren: "B2",
  reflektieren: "B2",
  priorisieren: "B2",
  optimieren: "B2",
  koordinieren: "B2",
  evaluieren: "B2",
  implementieren: "B2",
  gewährleisten: "B2",
  thematisieren: "B2",
  vermitteln: "B2",
  bewerten: "B2",
  fördern: "B2",
  einschränken: "B2",
  "sich bewähren": "B2",
  // Nouns B2
  auswirkung: "B2",
  einschätzung: "B2",
  überzeugung: "B2",
  umsetzung: "B2",
  vereinbarung: "B2",
  zustimmung: "B2",
  tendenz: "B2",
  begründung: "B2",
  ablehnung: "B2",
  einschränkung: "B2",
  aufwand: "B2",
  bestandteil: "B2",
  umfang: "B2",
  vorwurf: "B2",
  standpunkt: "B2",
  verfügbarkeit: "B2",
  wahrnehmung: "B2",
  nachhaltigkeit: "B2",
  eindruck: "B2",
  widerspruch: "B2",
  zivilgesellschaft: "B2",
  kompromiss: "B2",
  anforderung: "B2",
  schwerpunkt: "B2",
  rahmenbedingung: "B2",
  herkunft: "B2",
  wirkung: "B2",
  maßnahme: "B2",
  grundlage: "B2",
  konzept: "B2",
  strategie: "B2",
  perspektive: "B2",
  kontext: "B2",
  faktor: "B2",
  ressource: "B2",
  effizienz: "B2",
  qualität: "B2",
  transparenz: "B2",
  demokratie: "B2",
  gerechtigkeit: "B2",
  eigenverantwortung: "B2",
  // Adjectives B2
  einleuchtend: "B2",
  umfangreich: "B2",
  komplex: "B2",
  vielfältig: "B2",
  differenziert: "B2",
  fundiert: "B2",
  relevant: "B2",
  effizient: "B2",
  konkret: "B2",
  abstrakt: "B2",
  kritisch: "B2",
  konstruktiv: "B2",
  produktiv: "B2",
  // ── C1 ───────────────────────────────────────────────────────────────────
  // Verbs C1
  validieren: "C1",
  verallgemeinern: "C1",
  disambiguieren: "C1",
  falsifizieren: "C1",
  plausibilisieren: "C1",
  operationalisieren: "C1",
  subsumieren: "C1",
  konzeptualisieren: "C1",
  extrapolieren: "C1",
  abstrahieren: "C1",
  // Nouns C1
  abhandlung: "C1",
  evidenz: "C1",
  empirie: "C1",
  erkenntnis: "C1",
  verallgemeinerung: "C1",
  standpunktvermittlung: "C1",
  unerlässlichkeit: "C1",
  plausibilität: "C1",
  paradigma: "C1",
  diskurs: "C1",
  implikation: "C1",
  konnotation: "C1",
  denotation: "C1",
  ambiguität: "C1",
  subjektivität: "C1",
  objektivität: "C1",
  axiom: "C1",
  hypothese: "C1",
  prämisse: "C1",
  schlussfolgerung: "C1",
  kontroverse: "C1",
  konstellation: "C1",
  disposition: "C1",
  qualifikation: "C1",
  kompetenz: "C1",
  kohärenz: "C1",
  kongruenz: "C1",
  divergenz: "C1",
  kontextualisierung: "C1",
  // Adjectives C1
  unerlässlich: "C1",
  vermeintlich: "C1",
  plausibel: "C1",
  stringent: "C1",
  kohärent: "C1",
  konsistent: "C1",
  inkonsistent: "C1",
  subtil: "C1",
  nuanciert: "C1",
  prägnant: "C1",
  sukzessiv: "C1",
  signifikant: "C1",
  implizit: "C1",
  explizit: "C1",
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Look up the CEFR level for a German word.
 * Strips the article (der/die/das/ein/eine) automatically.
 * Returns the level string or null if the word is not in the reference list.
 */
export function lookupCefrLevel(word: string): string | null {
  const clean = word
    .trim()
    .toLowerCase()
    .replace(/^(der|die|das|ein|eine)\s+/i, "");
  return CEFR_MAP[clean] ?? null;
}

/**
 * Returns the correct CEFR level for a word, preferring the reference list
 * over the AI-supplied level. Falls back to `aiLevel` if the word is unknown.
 *
 * @param word     - German word (with or without article)
 * @param aiLevel  - Level suggested by the AI
 */
export function correctLevel(word: string, aiLevel: string): string {
  return lookupCefrLevel(word) ?? aiLevel;
}

/** All levels in ascending order. */
export const CEFR_LEVELS = ["A1", "A2", "B1", "B2", "C1"] as const;
export type CefrLevel = (typeof CEFR_LEVELS)[number];
