uploads = []

[[generated]]
id = "oRYA8vuIgmAEnYaaBVYDO"
uri = "file://artifacts/german-flashcards-mobile/assets/images/icon.png"
type = "image"
title = "german flashcard app icon"

[[generated]]
id = "QI4f4lK6ebwnVOhR0jdik"
uri = "file://artifacts/german-flashcards-mobile/assets/images/splash-icon.png"
type = "image"
title = "german flashcard splash"

[[generated]]
id = "0primnodgQ3vl7068_Uuh"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "deutschkarten app icon"

[[outputs]]
id = "RSyFT-XUW_SiTRWbgp837"
uri = "file://deutschkarten.tar.gz"
type = "unspecified"
title = "DeutschKarten — Full Source Code"

[[outputs]]
id = "HhdjMlBornOU-RmXDUGA1"
uri = "file://deutschkarten-kivy.tar.gz"
type = "unspecified"
title = "DeutschKarten — Kivy Python App (fixed)"
